#!/usr/bin/env python3
"""Draw the mark into every form the site needs, from tools/logo.py.

    python3 tools/build_logo.py [docs/assets]

Emits:

    logo.svg        the mark alone, in its own navy and gold
    favicon.svg     the mark on its tile, for the browser tab
    icon-180.png    the tile, full bleed, for an iOS home screen
    icon-512.png    the tile, full bleed, for link previews and elsewhere
    lockup.svg      the mark over the wordmark, for a press kit or a card

Why a rasteriser lives in this repository at all: the site ships no
dependencies and the build runs on nothing but Python and Node, and a
logo that can only be regenerated by installing an image library is a
logo that stops being regenerated. The mark is ten filled paths, so the
rasteriser has to do polygons -- quadratics flattened by tools/logo.py,
then coverage measured by sampling each pixel on a 4 x 4 grid, which
gives clean edges at every size we emit without a matrix library.
"""

from __future__ import annotations

import os
import struct
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from logo import (BOX, GOLD, NAVY, PAPER, flatten,  # noqa: E402
                  shapes, svg_paths)

# Read in main() rather than here, so importing this module cannot pick
# up the arguments of whatever imported it.
OUT = "docs/assets"

# The tile: the mark inset in a square. 1/8 of the square on every side is
# the padding Apple's own icons use, and it survives the corner rounding
# that iOS applies over the top of whatever we send it.
PAD = 1.0 / 8.0

SAMPLES = 4                                     # per pixel, per axis


def inside(px: float, py: float, poly: list) -> bool:
    """Is this point inside the polygon? Crossing count, so odd is in.

    The mark's leaves are simple closed curves that do not cross themselves,
    so the even-odd rule and the winding rule agree and this is the cheaper
    of the two.
    """
    hit = False
    n = len(poly)
    j = n - 1
    for i in range(n):
        yi, yj = poly[i][1], poly[j][1]
        if (yi > py) != (yj > py):
            x = poly[i][0] + (py - yi) * (poly[j][0] - poly[i][0]) / (yj - yi)
            if px < x:
                hit = not hit
        j = i
    return hit


def fill(pixels: bytearray, size: int, poly: list,
         rgb: tuple[int, int, int]) -> None:
    """Lay one polygon down, sampling each pixel on a SAMPLES x SAMPLES grid.

    Coverage rather than a hard test, which is the whole reason this is here
    and not a one-line call to something: the edges have to stay clean at 180
    and 512 without a matrix library or an image library to do it.
    """
    xs = [p[0] for p in poly]
    ys = [p[1] for p in poly]
    x0 = max(0, int(min(xs)) - 1)
    x1 = min(size, int(max(xs)) + 2)
    y0 = max(0, int(min(ys)) - 1)
    y1 = min(size, int(max(ys)) + 2)

    step = 1.0 / SAMPLES
    half = step / 2.0

    for py in range(y0, y1):
        for px in range(x0, x1):
            hits = 0
            for sy in range(SAMPLES):
                for sx in range(SAMPLES):
                    if inside(px + sx * step + half,
                              py + sy * step + half, poly):
                        hits += 1
            if not hits:
                continue
            a = hits / (SAMPLES * SAMPLES)
            i = (py * size + px) * 3
            for c in range(3):
                under = pixels[i + c]
                pixels[i + c] = round(under + (rgb[c] - under) * a)


def raster(size: int, ground: tuple[int, int, int]) -> bytes:
    """The tile at size x size, as RGB rows, ready for PNG packing."""
    pixels = bytearray()
    for _ in range(size * size):
        pixels += bytes(ground)

    scale = size * (1.0 - 2 * PAD) / BOX
    off = size * PAD

    for path, rgb in shapes():
        poly = [(x * scale + off, y * scale + off)
                for x, y in flatten(path)]
        fill(pixels, size, poly, rgb)

    rows = bytearray()
    for py in range(size):
        rows.append(0)                          # filter: none
        rows += pixels[py * size * 3:(py + 1) * size * 3]
    return bytes(rows)


def png(size: int) -> bytes:
    """Minimal 8-bit RGB PNG. Deterministic, so a rebuild is a no-op."""
    def chunk(tag: bytes, body: bytes) -> bytes:
        return (struct.pack(">I", len(body)) + tag + body
                + struct.pack(">I", zlib.crc32(tag + body) & 0xFFFFFFFF))

    head = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", head)
            + chunk(b"IDAT", zlib.compress(raster(size, PAPER), 9))
            + chunk(b"IEND", b""))


MARK_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" \
width="24" height="24" role="img" aria-label="The Book">
  <title>The Book</title>
  {paths}
</svg>
"""

TILE_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" \
width="64" height="64" role="img" aria-label="The Book">
  <title>The Book</title>
  <rect width="64" height="64" rx="14" fill="{bg}"/>
  {paths}
</svg>
"""


def hexc(rgb: tuple[int, int, int]) -> str:
    return "#%02x%02x%02x" % rgb


# The full lockup: the mark over the wordmark, with the rules and the two
# lines under it. Only for the places that want the whole signature -- a
# press kit, a social card -- rather than an icon.
#
# The type is set in <text> with a stack rather than converted to outlines,
# because outlines would mean shipping a font parser to a repository whose
# rule is that the build runs on nothing but Python and Node. The cost is
# real and worth knowing: the wordmark renders in whatever serif the viewer
# has, so this is not the file to hand a printer. The mark above it is
# geometry and is exact everywhere.
LOCKUP_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 700" \
width="600" height="700" role="img" aria-label="The Book — Chronological \
Biblical Library">
  <title>The Book — Chronological Biblical Library</title>
  <g>
  {paths}
  </g>
  <path d="M300 331 l9 9 -9 9 -9 -9Z" fill="{gold}"/>
  <path d="M170 349 H430" stroke="{gold}" stroke-width="2"/>
  <text x="300" y="446" text-anchor="middle" fill="{navy}" \
font-family="{serif}" font-size="86">The</text>
  <text x="300" y="546" text-anchor="middle" fill="{navy}" \
font-family="{serif}" font-size="150">Book</text>
  <path d="M112 594 H286" stroke="{gold}" stroke-width="2"/>
  <path d="M300 585 l9 9 -9 9 -9 -9Z" fill="{gold}"/>
  <path d="M314 594 H488" stroke="{gold}" stroke-width="2"/>
  <text x="302" y="632" text-anchor="middle" fill="{navy}" \
font-family="{sans}" font-size="22" letter-spacing="3.2">CHRONOLOGICAL \
BIBLICAL LIBRARY</text>
  <path d="M186 658 H288" stroke="{gold}" stroke-width="1.5"/>
  <circle cx="300" cy="658" r="4" fill="{gold}"/>
  <path d="M312 658 H414" stroke="{gold}" stroke-width="1.5"/>
  <text x="302" y="690" text-anchor="middle" fill="{navy}" \
font-family="{sans}" font-size="18" letter-spacing="3.4">SCRIPTURE · \
HISTORY · TRUTH</text>
</svg>
"""

SERIF = ("Iowan Old Style, Palatino Linotype, Palatino, Book Antiqua, "
         "Georgia, serif")
SANS = ("ui-sans-serif, system-ui, Segoe UI, Helvetica Neue, Arial, sans-serif")


def main() -> int:
    global OUT
    if len(sys.argv) > 1:
        OUT = sys.argv[1]
    os.makedirs(OUT, exist_ok=True)

    written = []

    # The mark in its own colours, for the page and the README.
    mark = MARK_SVG.format(paths=svg_paths())
    _write(os.path.join(OUT, "logo.svg"), mark.encode("utf-8"), written)

    # The tile: paper ground, so navy boards and gold leaves both read. A
    # navy ground would swallow the boards and leave the leaves floating.
    inset = 64 * PAD
    tile = TILE_SVG.format(
        bg=hexc(PAPER),
        paths=svg_paths(scale=64 * (1 - 2 * PAD) / BOX, dx=inset, dy=inset))
    _write(os.path.join(OUT, "favicon.svg"), tile.encode("utf-8"), written)

    for size in (180, 512):
        _write(os.path.join(OUT, f"icon-{size}.png"), png(size), written)

    # The mark sits in the top third of the lockup, 300 wide and centred.
    lock = LOCKUP_SVG.format(
        paths=svg_paths(scale=300 / BOX, dx=150, dy=42),
        navy=hexc(NAVY), gold=hexc(GOLD), serif=SERIF, sans=SANS)
    _write(os.path.join(OUT, "lockup.svg"), lock.encode("utf-8"), written)

    for name, n in written:
        print(f"  {name}  {n:,} bytes")
    return 0


def _write(path: str, data: bytes, written: list) -> None:
    with open(path, "wb") as fh:
        fh.write(data)
    written.append((os.path.relpath(path), len(data)))


if __name__ == "__main__":
    raise SystemExit(main())
