#!/usr/bin/env python3
"""Draw the mark into every form the site needs, from tools/logo.py.

    python3 tools/build_logo.py [docs/assets]

Emits:

    logo.svg        the mark alone, in currentColor, for the page and README
    favicon.svg     the mark on its tile, for the browser tab
    icon-180.png    the tile, full bleed, for an iOS home screen
    icon-512.png    the tile, full bleed, for link previews and elsewhere

Why a rasteriser lives in this repository at all: the site ships no
dependencies and the build runs on nothing but Python and Node, and a
logo that can only be regenerated by installing an image library is a
logo that stops being regenerated. The mark is five rounded rectangles,
so the rasteriser only has to do rounded rectangles, and it does that
exactly -- coverage is measured by sampling each pixel on a 4 x 4 grid,
which gives clean edges at every size we emit without a matrix library.
"""

from __future__ import annotations

import os
import struct
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from logo import ACCENT, BOX, PAPER, radius, rects, svg_paths  # noqa: E402

# Read in main() rather than here, so importing this module cannot pick
# up the arguments of whatever imported it.
OUT = "docs/assets"

# The tile: the mark inset in a square. 1/8 of the square on every side is
# the padding Apple's own icons use, and it survives the corner rounding
# that iOS applies over the top of whatever we send it.
PAD = 1.0 / 8.0

SAMPLES = 4                                     # per pixel, per axis


def covered(px: float, py: float, x: float, y: float,
            w: float, h: float, r: float) -> bool:
    """Is this point inside the rounded rectangle?"""
    if px < x or py < y or px > x + w or py > y + h:
        return False
    # Inside the cross formed by the two inset rectangles: always covered.
    if x + r <= px <= x + w - r or y + r <= py <= y + h - r:
        return True
    cx = x + r if px < x + r else x + w - r
    cy = y + r if py < y + r else y + h - r
    return (px - cx) ** 2 + (py - cy) ** 2 <= r * r


def raster(size: int) -> bytes:
    """The tile at size x size, as RGB rows, ready for PNG packing."""
    pixels = bytearray()
    for _ in range(size * size):
        pixels += bytes(ACCENT)

    scale = size * (1.0 - 2 * PAD) / BOX
    off = size * PAD
    step = 1.0 / SAMPLES
    half = step / 2.0

    for rx, ry, rw, rh in rects():
        x, y = rx * scale + off, ry * scale + off
        w, h = rw * scale, rh * scale
        r = radius(min(rw, rh)) * scale
        for py in range(max(0, int(y)), min(size, int(y + h) + 2)):
            for px in range(max(0, int(x)), min(size, int(x + w) + 2)):
                hits = 0
                for sy in range(SAMPLES):
                    for sx in range(SAMPLES):
                        if covered(px + sx * step + half,
                                   py + sy * step + half, x, y, w, h, r):
                            hits += 1
                if not hits:
                    continue
                a = hits / (SAMPLES * SAMPLES)
                i = (py * size + px) * 3
                for c in range(3):
                    under = pixels[i + c]
                    pixels[i + c] = round(under + (PAPER[c] - under) * a)

    rows = bytearray()
    for py in range(size):
        rows.append(0)                          # filter: none
        rows += pixels[py * size * 3:(py + 1) * size * 3]
    return bytes(rows)


def png(size: int) -> bytes:
    """Minimal 8-bit RGB PNG. Deterministic, so a rebuild is a no-op."""
    def chunk(tag: bytes, body: bytes) -> bytes:
        return (struct.pack(">I", len(body)) + tag + body
                + struct.pack(">I", zlib.crc32(tag + body) & 0xFFFFFFFF))

    head = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", head)
            + chunk(b"IDAT", zlib.compress(raster(size), 9))
            + chunk(b"IEND", b""))


MARK_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" \
width="24" height="24" role="img" aria-label="The Book">
  <title>The Book</title>
  {paths}
</svg>
"""

TILE_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" \
width="64" height="64" role="img" aria-label="The Book">
  <title>The Book</title>
  <rect width="64" height="64" rx="14" fill="{bg}"/>
  {paths}
</svg>
"""


def hexc(rgb: tuple[int, int, int]) -> str:
    return "#%02x%02x%02x" % rgb


def main() -> int:
    global OUT
    if len(sys.argv) > 1:
        OUT = sys.argv[1]
    os.makedirs(OUT, exist_ok=True)

    written = []

    mark = MARK_SVG.format(paths=svg_paths())
    _write(os.path.join(OUT, "logo.svg"), mark.encode("utf-8"), written)

    inset = 64 * PAD
    tile = TILE_SVG.format(
        bg=hexc(ACCENT),
        paths=svg_paths(scale=64 * (1 - 2 * PAD) / BOX, dx=inset, dy=inset,
                        fill=hexc(PAPER)))
    _write(os.path.join(OUT, "favicon.svg"), tile.encode("utf-8"), written)

    for size in (180, 512):
        _write(os.path.join(OUT, f"icon-{size}.png"), png(size), written)

    for name, n in written:
        print(f"  {name}  {n:,} bytes")
    return 0


def _write(path: str, data: bytes, written: list) -> None:
    with open(path, "wb") as fh:
        fh.write(data)
    written.append((os.path.relpath(path), len(data)))


if __name__ == "__main__":
    raise SystemExit(main())
