#!/usr/bin/env python3
"""The service worker, stamped with a hash of everything it serves.

    python3 tools/build_sw.py docs

The worker is network-first and never anything else. Online, every request
goes to the network and the cache is written from the answer; the cache is
read only when the network has actually failed. That is the whole design, and
it is a deliberate refusal of the usual one: stale-while-revalidate is faster
and would serve yesterday's chapter to somebody holding a phone with five
bars, which for a volume whose argument is that its claims carry citations is
the wrong trade at any speed. Nothing here can make the site less current
than it is without a worker.

What the stamp is for. A worker only updates when its own bytes change, and
the caches it holds outlive it. Hashing the files the worker serves means a
deploy that changes any of them changes this file, the browser installs the
new worker, and the activate step below drops every cache not carrying the
new stamp -- so a renamed or deleted file cannot sit in somebody's cache
being served forever after it stopped existing. The hash is of content, not
of the clock, so rebuilding without changing anything rewrites the same
bytes and shows up as no diff at all.

Output is docs/sw.js, which is derived and gitignored, like the crawlable
pages and the single-file copy: built here, built by the deploy, and never
committed.

Standard library only, like every other script here.
"""

import hashlib
import os
import sys

# Everything whose change should mean a new worker and a cleared cache. The
# worker itself is not in the list -- it is the output, and hashing it into
# itself has no fixed point.
HASHED = (
    "index.html",
    "site.webmanifest",
    "assets/app.js",
    "assets/app.css",
    "assets/sw-register.js",
    "data",
)

# How many data files a reader keeps. The works have a median of 16 KB and a
# mean of 43, so sixty is roughly one to three megabytes: enough that the
# chapters somebody actually reads are there on a train, and far short of
# quietly filling a phone with a twelve-megabyte library nobody asked for.
DATA_CAP = 60

TEMPLATE = '''/* Generated by tools/build_sw.py. Do not edit; edit that.
 *
 * Network-first, always. The cache is a fallback for a failed request and
 * never a shortcut for a slow one: there is no timeout that gives up on the
 * network and serves the copy, because "up to date unless the network is
 * slow" is not up to date. Online you get exactly what you would get with no
 * worker at all. Offline you get the last thing that was really fetched, and
 * the page says so.
 */

var VERSION = "%(stamp)s";
var SHELL = "shell-" + VERSION;
var DATA = "data-" + VERSION;
var DATA_CAP = %(cap)d;

/* Enough to open the reader with no network on the first try. The data is
   not in here: it is cached as it is fetched, because which works somebody
   reads is not knowable from here and precaching the library would be the
   twelve-megabyte download this deliberately avoids. */
var PRECACHE = [
  "./",
  "./index.html",
  "./assets/app.css",
  "./assets/app.js",
  "./assets/favicon.svg",
  "./site.webmanifest"
];

self.addEventListener("install", function (e) {
  e.waitUntil(
    caches.open(SHELL).then(function (c) {
      return c.addAll(PRECACHE);
    }).then(function () {
      /* Take over at once. Every response is network-first, so a new worker
         cannot serve anything staler than the old one would have. */
      return self.skipWaiting();
    })
  );
});

self.addEventListener("activate", function (e) {
  e.waitUntil(
    caches.keys().then(function (names) {
      return Promise.all(names.map(function (n) {
        /* Anything not carrying this build's stamp is a previous deploy's
           idea of the site. Dropping it is the only thing that stops a file
           deleted upstream from living in a cache for good. */
        if (n !== SHELL && n !== DATA) return caches.delete(n);
        return null;
      }));
    }).then(function () {
      return self.clients.claim();
    })
  );
});

/* The single-file copy is twelve megabytes of the whole library. robots.txt
   already keeps crawlers off it; this keeps it out of a phone's cache, where
   one navigation would spend more storage than every chapter somebody will
   ever read. */
function cacheable(url) {
  if (url.pathname.indexOf("/the-book.html") !== -1) return false;
  return true;
}

function trim(cache) {
  return cache.keys().then(function (keys) {
    if (keys.length <= DATA_CAP) return null;
    /* keys() is insertion order, so the front of it is the oldest thing put
       in. Evicting there makes this the least-recently-added rather than the
       least-recently-used, which for reading a book in order is the same
       thing often enough and needs no bookkeeping to do. */
    return Promise.all(keys.slice(0, keys.length - DATA_CAP).map(function (k) {
      return cache.delete(k);
    }));
  });
}

self.addEventListener("fetch", function (e) {
  var req = e.request;
  if (req.method !== "GET") return;

  var url;
  try { url = new URL(req.url); } catch (err) { return; }
  if (url.origin !== self.location.origin) return;
  if (!cacheable(url)) return;

  var isData = url.pathname.indexOf("/data/") !== -1;
  var box = isData ? DATA : SHELL;

  e.respondWith(
    fetch(req).then(function (res) {
      /* Only a real answer is worth keeping. A 404 or a redirect cached here
         would be served back offline as though it were the page. */
      if (res && res.status === 200 && res.type === "basic") {
        var copy = res.clone();
        caches.open(box).then(function (c) {
          return c.put(req, copy).then(function () {
            return isData ? trim(c) : null;
          });
        });
      }
      return res;
    }).catch(function () {
      return caches.match(req).then(function (hit) {
        if (hit) return hit;
        /* A navigation to a page never visited: the reader itself is
           cached, and it can route from the address once it is running. */
        if (req.mode === "navigate") {
          return caches.match("./index.html").then(function (shell) {
            return shell || new Response("Offline, and this page was never "
              + "fetched.", { status: 503, headers: { "Content-Type": "text/plain" } });
          });
        }
        return new Response("Offline.", { status: 503,
          headers: { "Content-Type": "text/plain" } });
      });
    })
  );
});
'''


def walk(root, rel):
    """Every file under a path, or the one file, sorted so the hash is stable."""
    full = os.path.join(root, rel)
    if os.path.isfile(full):
        return [full]
    found = []
    for folder, dirs, files in os.walk(full):
        dirs.sort()
        for name in sorted(files):
            found.append(os.path.join(folder, name))
    return sorted(found)


def stamp(root):
    """A hash over the content of everything the worker serves.

    Content and not a timestamp, so that a rebuild with nothing changed
    writes the same file. The path goes into the digest as well as the bytes,
    or a file renamed with its content untouched would not move the stamp.
    """
    h = hashlib.sha256()
    for rel in HASHED:
        for path in walk(root, rel):
            h.update(os.path.relpath(path, root).replace(os.sep, "/").encode())
            h.update(b"\0")
            with open(path, "rb") as fh:
                for block in iter(lambda: fh.read(1 << 20), b""):
                    h.update(block)
    return h.hexdigest()[:12]


def build(root):
    missing = [r for r in HASHED if not os.path.exists(os.path.join(root, r))]
    if missing:
        raise SystemExit("build_sw: nothing at " + ", ".join(missing))
    body = TEMPLATE % {"stamp": stamp(root), "cap": DATA_CAP}
    out = os.path.join(root, "sw.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(body)
    return out


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "docs"
    out = build(root)
    print("  %s  stamp %s" % (out, stamp(root)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
